### ISSUE TITLE
how to set chunk size?

### ISSUE THREAD

**Issue by xurwxj** [tomitrescak/meteor-tomi-upload-jquery#4]
is there a param to set chunk size?
jquery file upload support maxChunkSize.

**Comment by tomitrescak** [comment]
No, there is no explicit way of setting the chunk size. Pull requests are welcome. You only need to modify the Uploader.js file and add the configuration option. Thanks

**Comment by xurwxj** [comment]
oh, thx a lot.
i've got it.
