### ISSUE TITLE
demo link

### ISSUE THREAD

**Issue by avalanche1** [tomitrescak/meteor-tomi-upload-jquery#6]
Can't find the link to demo app...where is it?

**Comment by tomitrescak** [comment]
https://github.com/tomitrescak/meteor-uploads

**Comment by avalanche1** [comment]
It would be nice to deploy it to meteor.com for live demo.

**Comment by tomitrescak** [comment]
This plugin does not work on free meteor servers due to write protection
and creation of new directories.
On Wed, 10 Jun 2015 at 17:48 Artem Saffron <notifications@github.com> wrote:

> It would be nice to deploy it to meteor.com for live demo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomitrescak/meteor-tomi-upload-jquery/issues/6#issuecomment-110640381>
> .
>
-- 
~
Tomi Trescak / Researcher  tomi.trescak@gmail.com / 0487 261 213
